### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by skaex** [TeyimPila/tela-mis#1]
- [x] Models
  - [x] Tutor
  - [x] Beneficiary
  - [x] Venue
  - [x] LGAs
  - [x] Facilitator
  - [x] Centers
  - [x] Enumerator
  - [x] Assessment

Pull requests for this branch should be made to the branch `feature/add-models`.

Please note:
- Any other change should be made in a separate pull request.
- Reference this issue in any pull request that is made.

**Comment by TeyimPila** [comment]
@SkaeX so this means all of us will be creating all the models on the same branch (feature/add-models) right?
